[package]
name = "shinkai-node"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
prost-build = "0.8.0"

[dependencies]
prost = "0.8.0"
prost-derive = "0.8.0"
serde_json = "1.0.66"
chacha20poly1305 = "0.7.1"
sha2 = "0.9.5"
x25519-dalek = "1.2.0"
rand_os = "0.2.2"
rand = "0.8"
base64 = "0.13.0"
tokio = { version = "1.0", features = ["full"] }
