[package]
name = "shinkai-node-ui"
version = "0.0.1"
description = "A Tauri App"
authors = ["nico@shinkai.com"]
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }
reqwest = { version = "0.11.20", features = ["json", "tokio-native-tls", "blocking", "stream"] }

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.20", features = ["json", "tokio-native-tls", "blocking", "stream"] }
tauri = { version = "1.5.4", features = [ "system-tray", "shell-open", "icon-ico", "icon-png"] }
serde_json = "1.0.105"
shinkai_node = { path = "../../../shinkai-node", features = ["stream"] }
config = "0.10"
toml = "0.5.8"
lazy_static = "1.4.0"
once_cell = "1.8.0"
async-channel = "1.6.1"
tokio = { version = "1.0", features = ["full"] }
libc = "0.2" # remove this

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
