[package]
name = "shinkai-node-ui"
version = "0.0.1"
description = "A Tauri App"
authors = ["nico@shinkai.com"]
license = "MIT"
repository = ""
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1.5.1", features = [] }
reqwest = { version = "0.11.20", features = ["json", "tokio-native-tls", "blocking", "stream"] }

[dependencies]
dotenv = "0.15.0"
reqwest = { version = "0.11.20", features = ["json", "tokio-native-tls", "blocking", "stream"] }
tauri = { version = "1.5", features = ["shell-open"] }
serde_json = "1.0.105"
shinkai_node = { path = "../../../shinkai-node", features = ["stream"] }

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
