NODE_IP = "0.0.0.0"
NODE_PORT = "9552"
NODE_API_IP = "0.0.0.0"
NODE_API_PORT = "9550"
IDENTITY_SECRET_KEY = "df3f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81119"
ENCRYPTION_SECRET_KEY = "d83f619804a92fdb4057192dc43dd748ea778adc52bc498ce80524c014b81159"
PING_INTERVAL_SECS = "0"
GLOBAL_IDENTITY_NAME = "@@localhost.shinkai"
RUST_LOG = "debug,error,info"
STARTING_NUM_QR_PROFILES = "1"
STARTING_NUM_QR_DEVICES = "1"
FIRST_DEVICE_NEEDS_REGISTRATION_CODE = "false"
LOG_SIMPLE = "true"
NO_SECRET_FILE = "true"
EMBEDDINGS_SERVER_URL = "https://internal.shinkai.com/x-embed-api/"
UNSTRUCTURED_SERVER_URL = "https://internal.shinkai.com/x-unstructured-api/"
STATIC_SERVER_PORT = "9554"
STATIC_SERVER_IP = "0.0.0.0"
STATIC_SERVER_FOLDER = "../../static_server_example"
INITIAL_AGENT_NAMES = "my_gpt,my_gpt_vision"
INITIAL_AGENT_URLS = "https://api.openai.com,https://api.openai.com"
INITIAL_AGENT_MODELS = "openai:gpt-4-1106-preview,openai:gpt-4-vision-preview"
RPC_URL = "https://rpc.sepolia.org"
CONTRACT_ADDRESS = "0x6964241D2458f0Fd300BB37535CF0145380810E0"
ABI_PATH = "Resources/ShinkaiRegistry.json"
INITIAL_AGENT_API_KEYS = "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,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"
LOG_ALL = 1