[package]
name = "shinkai_vector_resources"
version = "0.1.0"
edition = "2021"

[[test]]
name = "vector_resource_tests"
path = "tests/vector_resource_tests.rs"

[dependencies]
lazy_static = "1.4.0"
env_logger = "0.9"
anyhow = "1.0"
regex = "1"
csv = "1.1.6"
serde_json = "1.0.105"
byteorder = "1.4.3"
ordered-float = "3.7.0"
blake3 = "1.5.0"
keyphrases = "0.3.2"
async-trait = "0.1.74"
async-recursion = "1.0.5"
# llm = { git = "https://github.com/rustformers/llm", branch="main"} 

[build-dependencies]
reqwest = { version = "0.11", features = ["json", "tokio-native-tls", "blocking", "multipart"] }

[features]
default = ["native-http"]
native-http = ["reqwest/blocking"]
wasm-http = []

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["json", "tokio-native-tls", "blocking", "multipart", "default-tls"]

[dependencies.serde]
version = "1.0.188"
features = ["derive"]

[dev-dependencies]
tokio = { version = "1.0", features = ["full"] }
