[package]
name = "shinkai-dsl"
version = "0.1.0"
edition = "2021"

[dependencies]
pest = "2.7.10"
pest_derive = "2.7.10"
serde_json = "1.0"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]