openapi: 3.0.3
info:
  title: Shinkai Side Executor
  version: 0.1.0

servers:
  - url: http://localhost:8090
    description: Local default development server

tags:
  - name: PDF
    description: PDF related operations
  - name: VRKai
    description: VRKai related operations
  - name: VRPack
    description: VRPack related operations

paths:
  /v1/pdf/extract-to-text-groups:
    post:
      summary: Extract text from a PDF and returns an array of text groups
      tags:
        - PDF
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                max_node_text_size:
                  type: integer
                  default: 400
              required:
                - file
      responses:
        "200":
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/TextGroup"
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid request"
  /v1/vrkai/generate-from-file:
    post:
      summary: Generates a base64 encoded VRKai from a file
      tags:
        - VRKai
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                embedding_model:
                  type: string
                  default: snowflake-arctic-embed:xs
                embedding_gen_url:
                  type: string
                  default: https://internal.shinkai.com/x-embed-api/
                embedding_gen_key:
                  type: string
              required:
                - file
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /v1/vrkai/view-contents:
    post:
      summary: Returns a JSON representation of a VRKai
      tags:
        - VRKai
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                encoded_vrkai:
                  type: string
              required:
                - encoded_vrkai
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
        "400":
          description: Bad request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid request"
  /v1/vrpack/generate-from-files:
    post:
      summary: Generates a base64 encoded VRPack from files
      tags:
        - VRPack
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                embedding_model:
                  type: string
                  default: snowflake-arctic-embed:xs
                embedding_gen_url:
                  type: string
                  default: https://internal.shinkai.com/x-embed-api/
                embedding_gen_key:
                  type: string
                vrpack_name:
                  type: string
              required:
                - file
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string
  /v1/vrpack/generate-from-vrkais:
    post:
      summary: Generates a base64 encoded VRPack from VRKais
      tags:
        - VRPack
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: array
                  items:
                    type: string
                    format: binary
                vrpack_name:
                  type: string
              required:
                - file
      responses:
        "200":
          description: Successful response
          content:
            text/plain:
              schema:
                type: string

components:
  schemas:
    TextGroup:
      type: object
      properties:
        text:
          type: string
        metadata:
          type: object
          additionalProperties:
            type: string
        sub_groups:
          type: array
          items:
            $ref: "#/components/schemas/TextGroup"
        Embedding:
          $ref: "#/components/schemas/Embedding"
      required:
        - text
        - metadata
        - sub_groups
    Embedding:
      type: object
      properties:
        id:
          type: string
        vector:
          type: array
          items:
            type: number
      required:
        - id
        - vector
