[package]
name = "shinkai_sheet"
version = "0.1.0"
edition = "2021"

[dependencies]
serde_json = "1.0.117"
futures = "0.3.30"
tokio = { version = "1.36", features = ["full"] }
dashmap = "5.5.3"
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1.6.1", features = ["v4"] }
regex = "1"

[dependencies.serde]
version = "1.0.188"
features = ["derive"]
