name: Build shinkai-node binaries

on:
  push:
    branches:
      - "agallardol/ci-binaries"
    # tags:
    #   - '[0-9]+.[0-9]+.[0-9]+'
    #   - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build:
    name: Build binary
    strategy:
      matrix:
        include:
          - arch: x86_64-unknown-linux-gnu
            os: ubuntu-22.04
          - arch: aarch64-apple-darwin
            os: macos-14
    runs-on: ${{ matrix.os }}
    steps:
        - name: Checkout sources
          uses: actions/checkout@v4
    
        - name: Cache cargo assets
          id: cache
          uses: actions/cache@v4
          with:
            path: |
              ~/.cargo/bin/
              ~/.cargo/registry/index/
              ~/.cargo/registry/cache/
              ~/.cargo/git/db/
              target/
            key: ${{ matrix.arch }}-build-cargo-${{ hashFiles('**/Cargo.lock') }}

        - name: Build
          run: cargo build

        - name: Upload ${{ matrix.arch }} artifact
          uses: actions/upload-artifact@v4
          with:
            name: shinkai-node-${{ matrix.arch }}
            path: ./target/release/shinkai_node
